# Generated by Django 4.2 on 2026-02-06 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_leaverequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('holiday_date', models.DateField(primary_key=True, serialize=False)),
                ('holiday_day', models.CharField(max_length=10)),
                ('holiday_indicator', models.CharField(choices=[('Y', 'Holiday'), ('N', 'Non-Holiday')], default='N', max_length=1)),
                ('holiday_reason', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Holiday',
                'verbose_name_plural': 'Holidays',
                'db_table': 'holiday',
                'ordering': ['holiday_date'],
            },
        ),
    ]
