# Generated by Django 4.2 on 2026-02-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='comment_by_manager',
            field=models.TextField(blank=True, null=True),
        ),
    ]
